### ISSUE TITLE
luci界面的怎么选择配置呀

### ISSUE THREAD

**Issue by Qpeng111** [jimlee2002/openwrt-minieap-gdufs#1]
![image](https://user-images.githubusercontent.com/48241390/162600784-71250546-2522-47b7-80c4-ff4292944c6f.png)
![image](https://user-images.githubusercontent.com/48241390/162600785-03da2b25-efea-4238-b287-de21ce3e029c.png)
![image](https://user-images.githubusercontent.com/48241390/162600787-80589b17-6410-4c50-b6ca-522934f963a0.png)

**Comment by jimlee2048** [comment]
请参考 https://github.com/jimlee2002/minieap-gdufs/issues/2#issuecomment-1079910112
